In [191]:

from random import randint as ran
import numpy as np



. Write a program that generates and prints 50 random integers, each between 3 and 6

In [59]:
x  = ran(3,6)
y = []
for i in range(50):
    y.append(x)
print(y)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


Write a program that generates a random number, x, between 1 and 50, a random number y
between 2 and 5, and computes $x^y$
.

In [69]:
x = ran(1,50)
y = ran(2,5)
print('x = ',x,'\n','y = ',y)
print(x**y)

x =  30 
 y =  2
900


Write a program that generates a random number between 1 and 10 and prints your name
that many times.

In [72]:
z = ran(1,10)
name = 'Kofi'
print('random number is ',z)
for i in range(z):
    print(name)

random number is  2
Kofi
Kofi


 Write a program that generates 50 random numbers such that the first number is between 1
and 2, the second is between 1 and 3, the third is between 1 and 4, . . . , and the last is between
1 and 51

In [186]:
y = []
for i in range(1,51):
    y.append(ran(1,i+1))  
print(y)

#print("%0.2f"%x)

[1, 2, 1, 4, 6, 3, 5, 7, 4, 4, 5, 8, 4, 13, 3, 9, 17, 5, 9, 20, 7, 20, 9, 7, 2, 12, 22, 10, 27, 17, 31, 23, 2, 15, 8, 8, 24, 16, 20, 17, 18, 16, 30, 12, 16, 6, 20, 32, 4, 4]
50


Write a program thatasks the user to enter two numbers,$x$and$y$ and compute $\frac{|x-y|}{x+y}$.

In [201]:
import math
x  = float(input('Enter first number'))
y  = float(input('Enter second number'))

print('x: ',x)
print('y: ',y)
print(abs(x-y)/(x+y))


x:  3.0
y:  4.0
0.14285714285714285


Write a program that asks the user to enter an angle between −180◦
and 180◦
. Using an
expression with the modulo operator, convert the angle to its equivalent between 0
◦
and
360◦
.

In [211]:
a = float(input('Enter angle between -180 and 180'))
print('Angle:',a )
print(a%360)

Angle: -145.0
215.0


. Write a program that asks the user for a number of seconds and prints out how many minutes
and seconds that is. For instance, 200 seconds is 3 minutes and 20 seconds. [Hint: Use the //
operator to get minutes and the % operator to get seconds.]

In [218]:
a = int(input('Enter the number of seconds'))

if a<60:
    print(a,'secs')
else:
    b = a//60
    c = a%60
    print('input: ',a)
    print(b,'mins ',c,'secs')
    

input:  321
5 mins  21 secs


 Write a program that asks the user for an hour between 1 and 12 and for how many hours in
the future they want to go. Print out what the hour will be that many hours into the future.
An example is shown below

Enter hour: 8

How many hours ahead? 5

New hour: 1 o'clock


In [223]:
a = int(input('Enter hour: '))
b = int(input('how many hours ahead: '))
newHour = (a+b)%12
# print('a: ',a)
# print('b',b)
print('New hour is ', newHour , "o'clock")

a:  8
b 8
New hour is  4 o'clock


(a) One way to find out the last digit of a number is to mod the number by 10. Write a
program that asks the user to enter a power. Then find the last digit of 2 raised to that
power.

(b) One way to find out the last two digits of a number is to mod the number by 100. Write
a program that asks the user to enter a power. Then find the last two digits of 2 raised to
that power.

(c) Write a program that asks the user to enter a power and how many digits they want.
Find the last that many digits of 2 raised to the power the user entered.

In [233]:
#(a)
a = int(input('Enter a power: '))


b = (2**a)%10
print('the last digit is ', b)

the last digit is  6


In [235]:
#(b)
a = int(input('Enter a power: '))


b = (2**a)%100
print('the last two digit is ', b)

the last two digit is  76


In [255]:
#(c)
a = int(input('Enter a power: '))
c = int(input('How many last digits do you want: '))

# below is a refence

# c = 2      assumed number of digets user wants 

# y ='1'    we equate to y to 1 in string format 

# z = '0'*2  since user wants 2 digits, we multiply 0 by 2 in string format

# x = int(y + z) here we concatinate(join) the two strings and covert to int to obtain 100 as required




d = int('1' + ('0'*c))  #this is a combination of the above buh in this case c varies
b = (2**a)%d
print('the last two digit is ', b)

the last two digit is  6703205376


<class 'int'>


Write a program that draws “modular rectangles” like the ones below. The user specifies the
width and height of the rectangle, and the entries start at 0 and increase typewriter fashion
from left to right and top to bottom, but are all done mod 10. Below are examples of a 3 × 5
rectangle and a 4 × 8

0 1 2 3 4

5 6 7 8 9

0 1 2 3 4


In [266]:
h = int(input('specify the height: '))
w = int(input('specify the width: '))

x = np.arange(w*h).reshape(h,w)
print(x%10)




[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]]
